server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  kafka:
    bootstrap-servers: 127.0.0.1:3881,127.0.0.1:3882,127.0.0.1:3883
    producer:
      retries: 1
      batch-size: 16384
      client-id: 1
      group-id: 1
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
datasource:
  url: jdbc:mysql://120.79.77.11:3784/demorocket
  username: root
  password: HaoHao_112
  driverName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:com/tml/springkafka/mapper/*

